### ISSUE TITLE
not work with docker image mediawiki:1.35.4

### ISSUE THREAD

**Issue by jihch** [kuenzign/WikiMarkdown#1]
let me know if u need more info

**Comment by jihch** [comment]
wfLoadExtension( 'WikiMarkdown' ); done
$wgAllowMarkdownExtra = true; done
"Add the line "extensions/WikiMarkdown/composer.json" to the "composer.local.json" file in the root directory of your wiki" done

**Comment by kuenzign** [comment]
Please describe how it isn't working.  Is there an error being displayed?

**Comment by jihch** [comment]
> Please describe how it isn't working. Is there an error being displayed?

enviroment problem solved, something wrong when run command composer install with composer 2.3.10, 

![image](https://user-images.githubusercontent.com/10190659/181677651-0f5f7d06-11e1-48ce-8e65-83ff91b404e0.png)

problem like this one:
https://sourceforge.net/p/semediawiki/mailman/message/37408672/

after composer downgrade to 2.1.14, solved
