### ISSUE TITLE
Not working in docker

### ISSUE THREAD

**Issue by AraAraOwO** [kuenzign/WikiMarkdown#16]
1. It is not working in docker, it breaks VisualEditor,User menu, notification button, etc.
2. I tried running `composer install --no-dev` in its folder, got error that it needs php 7.0 which i fixed by running `composer config platform.php 7.0` then 7.2 then 7.2.9. After that it runs install command even on 8.1.29 BUT throws ' Error: Class "ParsedownExtended" not found' even though i am not using extended config

**Comment by charltonstanley** [comment]
>Error: Class "ParsedownExtended" not found

I fixed this by changing the composer.json file in this project to require *exactly* version `1.1.2` of ParsedownExtended.

Change:
```
"benjaminhoegh/parsedown-extended": "^1.1.2"
```
To:
```
"benjaminhoegh/parsedown-extended": "1.1.2"
```

The developer of ParsedownExtended seems to release major/breaking changes in his minor versions as opposed to his major versions. Before I changed this I was getting version `1.3.0` of ParsedownExtended when I ran `composer install`, which according to the ParsedownExtended [1.3.0 release page](https://github.com/BenjaminHoegh/ParsedownExtended/releases/tag/v1.3.0) includes significant changes/additions.

@kuenzign Could you take a look a this when you get a chance please? Without a fix for this, the installation instructions for your extension don't work.

**Comment by kuenzign** [comment]
I am hoping to upgrade the extension to support MediaWiki 1.43 when that is released.  I also plan to support newer versions of ParsedownExtended when that change is done.  In the meantime, if you provide a pull request, for this stopgap then I will merge it in.

**Comment by charltonstanley** [comment]
@kuenzign thanks for the prompt reply! PR Submitted (#17)
