### ISSUE TITLE
first line in code block with indent 

### ISSUE THREAD

**Issue by jihch** [kuenzign/WikiMarkdown#2]
before save:
![image](https://user-images.githubusercontent.com/10190659/181678411-673a1f0b-01dd-47f3-84ff-fbbbcf36b3a6.png)

after save:
![image](https://user-images.githubusercontent.com/10190659/181678200-3dbbe0b1-76e8-4600-8c14-2b1d3fa9a3b8.png)

just not align on vertical

**Comment by kuenzign** [comment]
Do you have the SyntaxHighlight extension installed?

**Comment by jihch** [comment]
> Do you have the SyntaxHighlight extension installed?

no.

i just checked the extensions directory，the SyntaxHighlight_GeSHi directory exists，but when i check the LocalSettings.php, no corresponding configuration，after i add wfLoadExtension( 'SyntaxHighlight_GeSHi' ); 

![image](https://user-images.githubusercontent.com/10190659/181724209-a43a2767-27a4-4ec4-98e9-e18ff9e9966b.png)

it seems everything is ok now.

![image](https://user-images.githubusercontent.com/10190659/181723771-1b3c5f9c-da6c-4e63-b34c-d7577f13eb3c.png)

align on vertical now,

thank u for your help
