### ISSUE TITLE
not work with Mathematical formula？

### ISSUE THREAD

**Issue by jihch** [kuenzign/WikiMarkdown#3]
source code:
![image](https://user-images.githubusercontent.com/10190659/183225848-3a5cb0e0-526c-41eb-bf37-99a8309312f9.png)

in markdown client like:
![image](https://user-images.githubusercontent.com/10190659/183225896-e7c9c506-d127-4824-8e68-73510376ddfc.png)

but in MediaWiki:

code editor
![image](https://user-images.githubusercontent.com/10190659/183225938-6c41b833-25cd-4ceb-86ad-11f5aa9b861f.png)

page view
![image](https://user-images.githubusercontent.com/10190659/183225967-20eb5004-3c99-48c0-8562-40e44ae488fb.png)

**Comment by kuenzign** [comment]
Looks like that would require using something such as the parsedown-extended add-on for Parsedown.  I'll also need to make changes on my end to make that work.  I think it should be possible though.  Give me a few days to look into it.
