### ISSUE TITLE
unable to link to page headings

### ISSUE THREAD

**Issue by charltonstanley** [kuenzign/WikiMarkdown#7]
Hi there, thank you for this extension! I've been relegated to have to write in documentation in "wiki text/format" at my company and this extension has finally set me free. lol :smile: 

I've noticed a couple of things that are different when writing pages in markdown. I'm wondering if they are configuration errors on my end.
1. I'm not sure if there are some table of contents specific tweaks that need to be made in order to support markdown, however it seems that the table of contents isn't created anymore.
2. if i link to other markdown headings within the same page, or on a different markdown page, the links don't actually take you to the heading. For example if i have a heading `## Delete a Branch`, I would expect to be able to create a link later on in document like this `[delete the branch](#delete-a-branch)` and when I click on it, have it take me to on the point on the page where that heading is. However this doesn't happen; clicking the link does nothing when on the same page. When the link is a different markdown page, it just takes me to the top of that page.

Again, thanks for the great extension!

**Comment by kuenzign** [comment]
Sadly the extension is unable to add headings to the table of contents.  I had looked into this previously and tried my best to get it as close as possible to regular wikitext, but I believe that changes to the MediaWiki software would be required in order to accomplish this.

As for linking to headings, try appending `markdown_` to the beginning of your heading name.  `#markdown_delete-a-branch` for example.

**Comment by charltonstanley** [comment]
Thank you for taking the time to reply!

>Sadly the extension is unable to add headings to the table of contents. I had looked into this previously and tried my best to get it as close as possible to regular wikitext, but I believe that changes to the MediaWiki software would be required in order to accomplish this.

Ah, that's too bad. Sounds like we might need another extension to automatically build a custom TOC based on which lines begin with  `#`; unfortunately in my searching for one, I didn't find one.

>As for linking to headings, try appending markdown_ to the beginning of your heading name. #markdown_delete-a-branch for example.

This worked like a charm and even works across pages. Thank you!

**Comment by kuenzign** [comment]
The problem with the table of contents is that it is handled all internally by the MediaWiki software and there currently (as of MediaWiki 1.35) no way to have extensions hook into that.  There would need to be a hook added into the core MediaWiki software to allow this to work.
